### ISSUE TITLE
Handle signals

### ISSUE THREAD

**Issue by Ahmedalshafy** [Pastifier/Minishell#21]
handling Ctlr-c, Ctlr-d and Ctlr-\ signals

**Comment by Pastifier** [comment]
# Signals:
## In `main()` (interactive mode):
* catch SIGINT and SIGQUIT
* SIGQUIT is ignored and does nothing. You can make it write "\b\b \b\b" if you want.
* SIGINT outputs a newline and redisplays the prompt.
## Right before `fork()`:
* SIGINT and SIGQUIT are ignored. Do that by defining different signal handlers.
## Inside the `fork()`:
* SIGINT and SIGQUIT are returned to their default behaviours (SIGDFLT)
## After the `wait()` in `interpret()`:
* They're returned to their original values.
* You can do that in the `main()`'s while loop if you want, but it gives me an uneasy feeling, so be careful. If anything unexpected happens, tell me.
